# Generated by Django 4.2 on 2024-06-13 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('detail', models.TextField(null=True)),
                ('priority', models.SmallIntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C')])),
                ('deadline', models.DateTimeField()),
                ('state', models.SmallIntegerField(choices=[(1, 'in progress'), (2, 'completed'), (3, 'waiting')], default=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
